/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeup.academico.ui;

import com.codeup.academico.Academico;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author anonimo
 */
public class AcademicoInterf extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AcademicoInterf.class.getName());
    private ArrayList<Academico> listAcademic = new ArrayList<>();

    /**
     * Creates new form AcademicoInterf
     */
    public AcademicoInterf() {
        initComponents();
    }
    
    // funcion para validar que el nombre no contenga numero
    private static boolean nameValidate(String name) throws Exception{
       for(char c : name.toCharArray()){ 
           if(Character.isDigit(c)){
                throw new Exception("el nombre no es valido");
           }
       }
       return true;
    }
    
    
    private static boolean emailValidate(String email) throws Exception{
        String regex = "^(.+)@(\\S+)$";
        
        boolean validate = email.matches(regex);
        
        if(!validate){
            throw new Exception("El email es invalido");
        }
        
        return true;
    }
      
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        nameStudent = new javax.swing.JLabel();
        insertName = new javax.swing.JTextField();
        courseStudent = new javax.swing.JLabel();
        insertCourse = new javax.swing.JTextField();
        emailStudent = new javax.swing.JLabel();
        insertEmail = new javax.swing.JTextField();
        IdEstudiante = new javax.swing.JLabel();
        insertid = new javax.swing.JTextField();
        saveData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        title.setText("Student System");

        nameStudent.setText("Name:");

        courseStudent.setText("Course:");

        insertCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCourseActionPerformed(evt);
            }
        });

        emailStudent.setText("Email:");

        insertEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertEmailActionPerformed(evt);
            }
        });

        IdEstudiante.setText("Id Student:");

        insertid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertidActionPerformed(evt);
            }
        });

        saveData.setText("Save");
        saveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Students", "Names", "Cousers", "Emails"
            }
        ));
        tableData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(insertid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(insertName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(courseStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insertCourse, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insertEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(saveData, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(316, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(IdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(insertCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(emailStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(saveData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertCourseActionPerformed

    private void insertEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertEmailActionPerformed

    private void insertidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertidActionPerformed

    private void saveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataActionPerformed
        // TODO add your handling code here:
        
        try{
            Academico academic = new Academico();
            
           
            String nameStudent = insertName.getText().trim();
       
            String emailStudent = insertEmail.getText().trim();
             
        
            String courseStudent = insertCourse.getText().trim();
               
            String idStudents = insertid.getText().trim();
        
            
            if(nameStudent.isEmpty() || emailStudent.isEmpty() || courseStudent.isEmpty() || idStudents.isEmpty()){
                throw new Exception("los campos debe de ser ingreados");
            };
            
            nameValidate(nameStudent);
            emailValidate(emailStudent);
            
            
                
            int idStudent;
           
            idStudent = Integer.parseInt(idStudents);
       
        
            academic.setName(nameStudent);
            academic.setEmail(emailStudent);
            academic.setCouser(courseStudent);
            academic.setIdStudent(idStudent);
        
       
            listAcademic.add(academic);
            
            Object[] fila = {academic.getIdStudent() ,academic.getName(),  academic.getCourse() ,academic.getEmail(), };
            
            
            DefaultTableModel model = (DefaultTableModel) tableData.getModel();
            model.addRow(fila);
            
            
           
            insertName.setText("");
            insertEmail.setText("");
            insertCourse.setText("");
            insertid.setText(""); 
        
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "la id debe de ser un numero valido");
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
  
    }//GEN-LAST:event_saveDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AcademicoInterf().setVisible(true));
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdEstudiante;
    private javax.swing.JLabel courseStudent;
    private javax.swing.JLabel emailStudent;
    private javax.swing.JTextField insertCourse;
    private javax.swing.JTextField insertEmail;
    private javax.swing.JTextField insertName;
    private javax.swing.JTextField insertid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameStudent;
    private javax.swing.JButton saveData;
    private javax.swing.JTable tableData;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}


/*

/ Obtener valores desde JTextField
    String nombre = insertName.getText();
    String curso = insertCourse.getText();
    int nota = Integer.parseInt(insertNota.getText());

    // Crear objeto y guardarlo en la lista
    Academico acad = new Academico(nombre, curso, nota);
    listaAcademicos.add(acad);

    // Agregar fila a la tabla
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    Object[] fila = {nombre, curso, nota};
    model.addRow(fila);

    // Limpiar los campos de texto
    insertName.setText("");
    insertCourse.setText("");
    insertNota.setText("");

*/