/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegistroAcademico.codeup.academico.ui;

import RegistroAcademico.codeup.academico.service.UsuarioService;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author anonimo
 */
public class JFrameLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameLogin.class.getName());

    UsuarioService usuarioService = new UsuarioService();

    /**
     * Creates new form JFrameLogin
     */
    public JFrameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBttnLogin = new javax.swing.JButton();
        jPasswFieldLogin = new javax.swing.JPasswordField();
        jBttnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("     Login");

        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario:");

        jLabel3.setText("  Contraseña:");

        jBttnLogin.setBackground(new java.awt.Color(102, 255, 102));
        jBttnLogin.setForeground(new java.awt.Color(30, 30, 30));
        jBttnLogin.setText("Login");
        jBttnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnLoginActionPerformed(evt);
            }
        });

        jPasswFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswFieldLoginActionPerformed(evt);
            }
        });

        jBttnSalir.setBackground(new java.awt.Color(255, 0, 0));
        jBttnSalir.setForeground(new java.awt.Color(30, 30, 30));
        jBttnSalir.setText("Salir");
        jBttnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addComponent(jTextUsuario)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jBttnSalir))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBttnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBttnSalir)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jBttnLogin)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void jPasswFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswFieldLoginActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_jPasswFieldLoginActionPerformed

    private void jBttnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnLoginActionPerformed
        // TODO add your handling code here:

        String user = jTextUsuario.getText().trim();
        char[] pass = jPasswFieldLogin.getPassword();

        
        if (user.isBlank() || pass.length == 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor complete todos los campos.\n\nUsuario y contraseña son obligatorios.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE
            );
            jPasswFieldLogin.setText(""); 

            
            if (user.isBlank()) {
                jTextUsuario.requestFocus();
            } else {
                jPasswFieldLogin.requestFocus();
            }
            return;
        }

       
        jBttnLogin.setEnabled(false);           
        jBttnLogin.setText("Validando...");     

     
        SwingWorker<Boolean, Void> worker = new SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() throws Exception {
                
                Thread.sleep(800);
                return usuarioService.autenticar(user, pass);
            }

            @Override
            protected void done() {
                try {
                    boolean ok = get();

                    
                    Arrays.fill(pass, '\0');
                    jPasswFieldLogin.setText(""); 

                    // Reactivar botón
                    jBttnLogin.setEnabled(true);        
                    jBttnLogin.setText("Login");        

                    if (ok) {
                       
                        JOptionPane.showMessageDialog(
                                JFrameLogin.this,
                                "¡Bienvenido " + user + "!\n\nAbriendo el sistema...",
                                "Acceso concedido",
                                JOptionPane.INFORMATION_MESSAGE
                        );

                       
                        SwingUtilities.invokeLater(() -> {
                            var frame = new JFrameRegistroEstudiante();
                            frame.setLocationRelativeTo(null);
                            frame.setVisible(true);

                            
                            JFrameLogin.this.dispose();
                        });

                    } else {
                        
                        String[] opciones = {"Reintentar", "Salir"};
                        int opcion = JOptionPane.showOptionDialog(
                                JFrameLogin.this,
                                "Las credenciales ingresadas no son válidas.\n\n"
                                + "Verifique su usuario y contraseña e intente nuevamente.",
                                "Error de autenticación",
                                JOptionPane.YES_NO_CANCEL_OPTION,
                                JOptionPane.ERROR_MESSAGE,
                                null,
                                opciones,
                                opciones[0]
                        );

                        switch (opcion) {
                            case 0: 
                                jTextUsuario.requestFocus();
                                jTextUsuario.selectAll();
                                break;
                            case 1: 
                                System.exit(0);
                                break;
                        }
                    }

                } catch (Exception e) {
                    
                    jBttnLogin.setEnabled(true);        
                    jBttnLogin.setText("Login");        

                    JOptionPane.showMessageDialog(
                            JFrameLogin.this,
                            "Error inesperado durante la autenticación:\n" + e.getMessage(),
                            "Error del sistema",
                            JOptionPane.ERROR_MESSAGE
                    );

                    e.printStackTrace();
                }
            }
        };

        worker.execute();
    }//GEN-LAST:event_jBttnLoginActionPerformed

    private void jBttnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBttnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnLogin;
    private javax.swing.JButton jBttnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswFieldLogin;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
